# This file defines the configuration of the iperf3 server
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3
spec:
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    command: ["iperf3", "-s"]
    ports:
      - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-service
spec:
  selector:
    app: iperf3
  ports:
    - name: tcp-port
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: udp-port
      protocol: UDP
      port: 5201
      targetPort: 5201
